name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            williamsct1/kasm-hashcat:latest
            williamsct1/kasm-hashcat:${{ github.sha }}

      - name: Update README
        run: |
          echo "# Kasm Hashcat Container" > README.md
          echo "Last updated: $(date)" >> README.md
          echo "Docker Hub: [williamsct1/kasm-hashcat](https://hub.docker.com/r/williamsct1/kasm-hashcat)" >> README.md
          cat README_TEMPLATE.md >> README.md

      - name: Commit README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README" || echo "No changes to commit"
          git push || echo "No changes to push"